name: iDisguise
main: de.robingrether.idisguise.iDisguise
version: ${project.version}
api-version: 1.13
author: RobinGrether
description: Disguise as a mob or other player
website: https://dev.bukkit.org/projects/idisguise
commands:
   disguise:
      description: Disguise.
      aliases: [dis, d]
   undisguise:
      description: Undisguise.
      aliases: [undis, ud]
   odisguise:
      description: Disguise others.
      aliases: [odis, od]
permissions:
   iDisguise.*:
      default: op
      children:
         iDisguise.admin: true
         iDisguise.help: true
         iDisguise.mob.*: true
         iDisguise.object.*: true
         iDisguise.player.display-name: true
         iDisguise.player.name.*: true
         iDisguise.random: true
         iDisguise.undisguise: true
         iDisguise.visibility.*: true
   iDisguise.admin:
      default: op
      children:
         iDisguise.others: true
         iDisguise.player.prohibited: true
         iDisguise.reload: true
         iDisguise.see-through: true
         iDisguise.undisguise.all: true
         iDisguise.undisguise.others: true
         iDisguise.update: true
   iDisguise.help:
      default: true
   iDisguise.mob.*:
      default: op
      children:
         iDisguise.mob.baby: true
         iDisguise.mob.bat: true
         iDisguise.mob.blaze: true
         iDisguise.mob.cave_spider: true
         iDisguise.mob.chicken: true
         iDisguise.mob.cod: true
         iDisguise.mob.cow: true
         iDisguise.mob.creeper: true
         iDisguise.mob.creeper.powered: true
         iDisguise.mob.custom-name: true
         iDisguise.mob.dolphin: true
         iDisguise.mob.donkey: true
         iDisguise.mob.drowned: true
         iDisguise.mob.elder_guardian: true
         iDisguise.mob.ender_dragon: true
         iDisguise.mob.enderman: true
         iDisguise.mob.enderman.block: true
         iDisguise.mob.endermite: true
         iDisguise.mob.evoker: true
         iDisguise.mob.ghast: true
         iDisguise.mob.giant: true
         iDisguise.mob.guardian: true
         iDisguise.mob.horse: true
         iDisguise.mob.husk: true
         iDisguise.mob.illusioner: true
         iDisguise.mob.iron_golem: true
         iDisguise.mob.llama: true
         iDisguise.mob.magma_cube: true
         iDisguise.mob.magma_cube.giant: true
         iDisguise.mob.mule: true
         iDisguise.mob.mushroom_cow: true
         iDisguise.mob.ocelot: true
         iDisguise.mob.ocelot.type.*: true
         iDisguise.mob.parrot: true
         iDisguise.mob.parrot.variant.*: true
         iDisguise.mob.phantom: true
         iDisguise.mob.phantom.giant: true
         iDisguise.mob.pig: true
         iDisguise.mob.pig.saddled: true
         iDisguise.mob.pig_zombie: true
         iDisguise.mob.polar_bear: true
         iDisguise.mob.pufferfish: true
         iDisguise.mob.rabbit: true
         iDisguise.mob.rabbit.type.*: true
         iDisguise.mob.salmon: true
         iDisguise.mob.sheep: true
         iDisguise.mob.sheep.color.*: true
         iDisguise.mob.shulker: true
         iDisguise.mob.silverfish: true
         iDisguise.mob.skeletal_horse: true
         iDisguise.mob.skeleton: true
         iDisguise.mob.slime: true
         iDisguise.mob.slime.giant: true
         iDisguise.mob.snowman: true
         iDisguise.mob.spider: true
         iDisguise.mob.squid: true
         iDisguise.mob.stray: true
         iDisguise.mob.tropical_fish: true
         iDisguise.mob.turtle: true
         iDisguise.mob.undead_horse: true
         iDisguise.mob.vex: true
         iDisguise.mob.villager: true
         iDisguise.mob.villager.profession.*: true
         iDisguise.mob.vindicator: true
         iDisguise.mob.witch: true
         iDisguise.mob.wither: true
         iDisguise.mob.wither_skeleton: true
         iDisguise.mob.wolf: true
         iDisguise.mob.wolf.collar.*: true
         iDisguise.mob.wolf.tamed: true
         iDisguise.mob.wolf.angry: true
         iDisguise.mob.zombie: true
         iDisguise.mob.zombie_villager: true
   iDisguise.mob.baby:
      default: op
   iDisguise.mob.bat:
      default: op
   iDisguise.mob.blaze:
      default: op
   iDisguise.mob.cave_spider:
      default: op
   iDisguise.mob.chicken:
      default: op
   iDisguise.mob.cod:
      default: op
   iDisguise.mob.cow:
      default: op
   iDisguise.mob.creeper:
      default: op
   iDisguise.mob.creeper.powered:
      default: op
   iDisguise.mob.custom-name:
      default: op
   iDisguise.mob.dolphin:
      default: op
   iDisguise.mob.donkey:
      default: op
   iDisguise.mob.drowned:
      default: op
   iDisguise.mob.elder_guardian:
      default: op
   iDisguise.mob.ender_dragon:
      default: op
   iDisguise.mob.enderman:
      default: op
   iDisguise.mob.enderman.block:
      default: op
   iDisguise.mob.endermite:
      default: op
   iDisguise.mob.evoker:
      default: op
   iDisguise.mob.ghast:
      default: op
   iDisguise.mob.giant:
      default: op
   iDisguise.mob.guardian:
      default: op
   iDisguise.mob.horse:
      default: op
   iDisguise.mob.husk:
      default: op
   iDisguise.mob.illusioner:
      default: op
   iDisguise.mob.iron_golem:
      default: op
   iDisguise.mob.llama:
      default: op
   iDisguise.mob.magma_cube:
      default: op
   iDisguise.mob.magma_cube.giant:
      default: op
   iDisguise.mob.mule:
      default: op
   iDisguise.mob.mushroom_cow:
      default: op
   iDisguise.mob.ocelot:
      default: op
      children:
         iDisguise.mob.ocelot.type.wild: true
   iDisguise.mob.ocelot.type.*:
      default: op
      children:
         iDisguise.mob.ocelot.type.black: true
         iDisguise.mob.ocelot.type.red: true
         iDisguise.mob.ocelot.type.siamese: true
         iDisguise.mob.ocelot.type.wild: true
   iDisguise.mob.ocelot.type.black:
      default: op
   iDisguise.mob.ocelot.type.red:
      default: op
   iDisguise.mob.ocelot.type.siamese:
      default: op
   iDisguise.mob.ocelot.type.wild:
      default: op
   iDisguise.mob.parrot:
      default: op
      children:
         iDisguise.mob.parrot.variant.red: true
   iDisguise.mob.parrot.variant.*:
      default: op
      children:
         iDisguise.mob.parrot.variant.blue: true
         iDisguise.mob.parrot.variant.cyan: true
         iDisguise.mob.parrot.variant.gray: true
         iDisguise.mob.parrot.variant.green: true
         iDisguise.mob.parrot.variant.red: true
   iDisguise.mob.parrot.variant.blue:
      default: op
   iDisguise.mob.parrot.variant.cyan:
      default: op
   iDisguise.mob.parrot.variant.gray:
      default: op
   iDisguise.mob.parrot.variant.green:
      default: op
   iDisguise.mob.parrot.variant.red:
      default: op
   iDisguise.mob.phantom:
      default: op
   iDisguise.mob.phantom.giant:
      default: op
   iDisguise.mob.pig:
      default: op
   iDisguise.mob.pig.saddled:
      default: op
   iDisguise.mob.pig_zombie:
      default: op
   iDisguise.mob.polar_bear:
      default: op
   iDisguise.mob.pufferfish:
      default: op
   iDisguise.mob.rabbit:
      default: op
      children:
         iDisguise.mob.rabbit.type.brown: true
   iDisguise.mob.rabbit.type.*:
      default: op
      children:
         iDisguise.mob.rabbit.type.black: true
         iDisguise.mob.rabbit.type.black-white: true
         iDisguise.mob.rabbit.type.brown: true
         iDisguise.mob.rabbit.type.gold: true
         iDisguise.mob.rabbit.type.salt-pepper: true
         iDisguise.mob.rabbit.type.killer: true
         iDisguise.mob.rabbit.type.white: true
   iDisguise.mob.rabbit.type.black:
      default: op
   iDisguise.mob.rabbit.type.black-white:
      default: op
   iDisguise.mob.rabbit.type.brown:
      default: op
   iDisguise.mob.rabbit.type.gold:
      default: op
   iDisguise.mob.rabbit.type.salt-pepper:
      default: op
   iDisguise.mob.rabbit.type.killer:
      default: op
   iDisguise.mob.rabbit.type.white:
      default: op
   iDisguise.mob.salmon:
      default: op
   iDisguise.mob.sheep:
      default: op
      children:
         iDisguise.mob.sheep.color.white: true
   iDisguise.mob.sheep.color.*:
      default: op
      children:
         iDisguise.mob.sheep.color.black: true
         iDisguise.mob.sheep.color.blue: true
         iDisguise.mob.sheep.color.brown: true
         iDisguise.mob.sheep.color.cyan: true
         iDisguise.mob.sheep.color.gray: true
         iDisguise.mob.sheep.color.green: true
         iDisguise.mob.sheep.color.light-blue: true
         iDisguise.mob.sheep.color.lime: true
         iDisguise.mob.sheep.color.magenta: true
         iDisguise.mob.sheep.color.orange: true
         iDisguise.mob.sheep.color.pink: true
         iDisguise.mob.sheep.color.purple: true
         iDisguise.mob.sheep.color.red: true
         iDisguise.mob.sheep.color.silver: true
         iDisguise.mob.sheep.color.white: true
         iDisguise.mob.sheep.color.yellow: true
   iDisguise.mob.sheep.color.black:
      default: op
   iDisguise.mob.sheep.color.blue:
      default: op
   iDisguise.mob.sheep.color.brown:
      default: op
   iDisguise.mob.sheep.color.cyan:
      default: op
   iDisguise.mob.sheep.color.gray:
      default: op
   iDisguise.mob.sheep.color.green:
      default: op
   iDisguise.mob.sheep.color.light-blue:
      default: op
   iDisguise.mob.sheep.color.lime:
      default: op
   iDisguise.mob.sheep.color.magenta:
      default: op
   iDisguise.mob.sheep.color.orange:
      default: op
   iDisguise.mob.sheep.color.pink:
      default: op
   iDisguise.mob.sheep.color.purple:
      default: op
   iDisguise.mob.sheep.color.red:
      default: op
   iDisguise.mob.sheep.color.silver:
      default: op
   iDisguise.mob.sheep.color.white:
      default: op
   iDisguise.mob.sheep.color.yellow:
      default: op
   iDisguise.mob.shulker:
      default: op
   iDisguise.mob.silverfish:
      default: op
   iDisguise.mob.skeletal_horse:
      default: op
   iDisguise.mob.skeleton:
      default: op
   iDisguise.mob.slime:
      default: op
   iDisguise.mob.slime.giant:
      default: op
   iDisguise.mob.snowman:
      default: op
   iDisguise.mob.spider:
      default: op
   iDisguise.mob.squid:
      default: op
   iDisguise.mob.stray:
      default: op
   iDisguise.mob.tropical_fish:
      default: op
   iDisguise.mob.turtle:
      default: op
   iDisguise.mob.undead_horse:
      default: op
   iDisguise.mob.vex:
      default: op
   iDisguise.mob.villager:
      default: op
      children:
         iDisguise.mob.villager.profession.farmer: true
   iDisguise.mob.villager.profession.*:
      default: op
      children:
         iDisguise.mob.villager.profession.blacksmith: true
         iDisguise.mob.villager.profession.butcher: true
         iDisguise.mob.villager.profession.farmer: true
         iDisguise.mob.villager.profession.librarian: true
         iDisguise.mob.villager.profession.priest: true
   iDisguise.mob.villager.profession.blacksmith:
      default: op
   iDisguise.mob.villager.profession.butcher:
      default: op
   iDisguise.mob.villager.profession.farmer:
      default: op
   iDisguise.mob.villager.profession.librarian:
      default: op
   iDisguise.mob.villager.profession.priest:
      default: op
   iDisguise.mob.vindicator:
      default: op
   iDisguise.mob.witch:
      default: op
   iDisguise.mob.wither:
      default: op
   iDisguise.mob.wither_skeleton:
      default: op
   iDisguise.mob.wolf:
      default: op
      children:
         iDisguise.mob.wolf.collar.red: true
   iDisguise.mob.wolf.collar.*:
      default: op
      children:
         iDisguise.mob.wolf.collar.black: true
         iDisguise.mob.wolf.collar.blue: true
         iDisguise.mob.wolf.collar.brown: true
         iDisguise.mob.wolf.collar.cyan: true
         iDisguise.mob.wolf.collar.gray: true
         iDisguise.mob.wolf.collar.green: true
         iDisguise.mob.wolf.collar.light-blue: true
         iDisguise.mob.wolf.collar.lime: true
         iDisguise.mob.wolf.collar.magenta: true
         iDisguise.mob.wolf.collar.orange: true
         iDisguise.mob.wolf.collar.pink: true
         iDisguise.mob.wolf.collar.purple: true
         iDisguise.mob.wolf.collar.red: true
         iDisguise.mob.wolf.collar.silver: true
         iDisguise.mob.wolf.collar.white: true
         iDisguise.mob.wolf.collar.yellow: true
   iDisguise.mob.wolf.collar.black:
      default: op
   iDisguise.mob.wolf.collar.blue:
      default: op
   iDisguise.mob.wolf.collar.brown:
      default: op
   iDisguise.mob.wolf.collar.cyan:
      default: op
   iDisguise.mob.wolf.collar.gray:
      default: op
   iDisguise.mob.wolf.collar.green:
      default: op
   iDisguise.mob.wolf.collar.light-blue:
      default: op
   iDisguise.mob.wolf.collar.lime:
      default: op
   iDisguise.mob.wolf.collar.magenta:
      default: op
   iDisguise.mob.wolf.collar.orange:
      default: op
   iDisguise.mob.wolf.collar.pink:
      default: op
   iDisguise.mob.wolf.collar.purple:
      default: op
   iDisguise.mob.wolf.collar.red:
      default: op
   iDisguise.mob.wolf.collar.silver:
      default: op
   iDisguise.mob.wolf.collar.white:
      default: op
   iDisguise.mob.wolf.collar.yellow:
      default: op
   iDisguise.mob.wolf.tamed:
      default: op
   iDisguise.mob.wolf.angry:
      default: op
   iDisguise.mob.zombie:
      default: op
   iDisguise.mob.zombie_villager:
      default: op
   iDisguise.object.*:
      default: op
      children:
         iDisguise.object.area_effect_cloud: true
         iDisguise.object.armor_stand: true
         iDisguise.object.boat: true
         iDisguise.object.custom-name: true
         iDisguise.object.ender_crystal: true
         iDisguise.object.falling_block: true
         iDisguise.object.item: true
         iDisguise.object.minecart: true
   iDisguise.object.area_effect_cloud:
      default: op
   iDisguise.object.armor_stand:
      default: op
   iDisguise.object.boat:
      default: op
   iDisguise.object.custom-name:
      default: op
   iDisguise.object.ender_crystal:
      default: op
   iDisguise.object.falling_block:
      default: op
   iDisguise.object.item:
      default: op
   iDisguise.object.minecart:
      default: op
   iDisguise.others:
      default: op
   iDisguise.player.display-name:
      default: op
   iDisguise.player.name.*:
      default: op
   iDisguise.player.prohibited:
      default: op
   iDisguise.random:
      default: op
   iDisguise.reload:
      default: op
   iDisguise.see-through:
      default: op
   iDisguise.undisguise:
      default: op
   iDisguise.undisguise.all:
      default: op
   iDisguise.undisguise.others:
      default: op
   iDisguise.update:
      default: op
   iDisguise.visibility.*:
      default: op
      children:
         iDisguise.visibility.list: true
         iDisguise.visibility.permission: true
   iDisguise.visibility.list:
      default: op
   iDisguise.visibility.permission:
      default: op